# Generated by Django 5.2.1 on 2025-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='novos_valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.TextField(default='SOME STRING', max_length=255)),
                ('hum', models.TextField(default='SOME STRING', max_length=255)),
                ('luz', models.TextField(default='SOME STRING', max_length=255)),
                ('press', models.TextField(default='SOME STRING', max_length=255)),
                ('gas', models.TextField(default='SOME STRING', max_length=255)),
                ('rpm', models.TextField(default='SOME STRING', max_length=255)),
                ('vento', models.TextField(default='SOME STRING', max_length=255)),
                ('ar', models.TextField(default='SOME STRING', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RGraficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datae', models.TextField(max_length=255)),
            ],
        ),
    ]
